name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo greeting
        run: echo "Hello CI/CD!"
